/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfe.view;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pfe.Extra;
import pfe.classes.AllConnection;
import static pfe.view.ParameterSeance.FinSeanceTime;
import static pfe.view.ParameterSeance.Salle;
import static pfe.view.ParameterSeance.filiere;

/**
 *
 * @author Electronic Store
 */
public class Seance extends javax.swing.JFrame implements Runnable, ThreadFactory {
    ParameterSeance prmtrSeance = new ParameterSeance ();
    public Extra extra = new Extra();
    AllConnection cnx = new AllConnection();
    ResultSet rs,rs1,rs2,rs3,rs5,email;
    DefaultTableModel tabelModel;
   private WebcamPanel panel = null;
    private Webcam webcam = null;

    private static final long serialVersionUID = 6441489157408381878L;
    private Executor executor = Executors.newSingleThreadExecutor(this);
    public Seance() {
        initComponents();
        initWebcam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tblstagiere = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        nomprof = new javax.swing.JLabel();
        heure = new javax.swing.JLabel();
        nmbrStgr = new javax.swing.JLabel();
        salleProf = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        result_field = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfe/view/logo-ofppt-1 (1).jpg"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 1440, 10));

        jPanel5.setBackground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1490, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 1490, 10));

        Tblstagiere.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "last_name", "first name", "heures_d'absence", "statut"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tblstagiere);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 770, 570));

        jLabel1.setText("nom Prof");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Heure");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, -1));

        jLabel4.setText("classe");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel3.setText("nombre stagiares");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jButton3.setText("Fin seance");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 90, -1, -1));
        jPanel3.add(nomprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 85, 20));

        heure.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(heure, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 120, 20));
        jPanel3.add(nmbrStgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 101, 20));
        jPanel3.add(salleProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 123, 20));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(126, 167, 206));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 470, 10));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 510));

        result_field.setBorder(null);
        jPanel2.add(result_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 510, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 780, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1574, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//            String flr =salleProf.getText();
            
            
                    
                    
        String absReq = "update stagiaire s set s.seance_absn = s.seance_absn+1 where s.statut=10 ";
        String reqUpdate ="update stagiaire s set s.statut = 10 ";
        String req2 ="select g.nomgroupe from groupe g";
        String dlt="DELETE FROM seance s WHERE  s.idgroupe = (select idgroupe from groupe where nomgroupe= '"+salleProf.getText()+"')";
//        String req = "Update classe c set c.statut = 3 where  c.numclasse= '"+Salle.getSelectedItem().toString()+"'";
//        String req3 ="Update Groupe c set c.STATUT = 4 where  c.Nomgroupe= '"+filiere.getSelectedItem().toString()+"'";
       rs = cnx.executerSelect(absReq);
       rs1 = cnx.executerSelect(reqUpdate);
       rs5=cnx.executerSelect(req2);
       cnx.executerSelect(dlt);
//       cnx.executerMAJ(req);
//       cnx.executerMAJ(req3);
                
//        new ParameterSeance().setVisible(true);            
//        panel.setFPSDisplayed(false);
        System.exit(0);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        java.util.Date date = Calendar.getInstance().getTime();
//        System.out.println(date);
                DateFormat dateFormat = new SimpleDateFormat("hh:mm");  
                String strDate = dateFormat.format(date);  
                heure.setText(strDate);
       String tm = FinSeanceTime.getSelectedTime();
       
        
            
        
        
        String flr =salleProf.getText();


       
            

                 String req ="select s.last_name, s.first_name,s.seance_absn,st.statut  from stagiaire s , statut st where (s.idgroupe = (select codegroupe from groupe where nomgroupe= '"+flr+"') and st.idstatut=s.statut)";
                rs = cnx.executerSelect(req);
                tabelModel = (DefaultTableModel) Tblstagiere.getModel();
                tabelModel.setRowCount(0);
          try {         
                        while ( rs.next()){
                            
                        tabelModel.addRow(
                                new Object[]{
                            rs.getString(1), 
                            rs.getString(2), 
                            rs.getInt(3), 
                            rs.getString(4)
                                     });
                        
                                
 
}
          }catch (SQLException ex) {
            System.out.println("windoesopened"+ex);
}
      
          
    
          
          
          
//  //send email notif a l'etudiant
//   String reqEmail = "select email from Stagiaire " ;
//   email =cnx.executerSelect(reqEmail);
//   try{
//       
//   while(email.next()){
//       String em = email.getString(1);
//   extra.sendEmail(em, "Votre Prof"+nomprof.getText()+" a demarer un seance");
// 
//   }
//   
//               
//   }catch(SQLException e){
//       System.out.println(e);
//   }
  
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               
                new Seance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tblstagiere;
    public static javax.swing.JLabel heure;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel nmbrStgr;
    public static javax.swing.JLabel nomprof;
    private javax.swing.JTextField result_field;
    public static javax.swing.JLabel salleProf;
    // End of variables declaration//GEN-END:variables
 private void initWebcam() {
        Dimension size = WebcamResolution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0); //0 is default webcam
        webcam.setViewSize(size);

        panel = new WebcamPanel(webcam);
        panel.setPreferredSize(size);
        panel.setFPSDisplayed(true);

        jPanel2.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 512));

        executor.execute(this);
    }

    @Override
    public void run() {
        do {
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            Result result = null;
            BufferedImage image = null;

            if (webcam.isOpen()) {
                if ((image = webcam.getImage()) == null) {
                    continue;
                }
            }

            LuminanceSource source = new BufferedImageLuminanceSource(image);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

            try {
                result = new MultiFormatReader().decode(bitmap);
            } catch (NotFoundException e) {
                //No result...
            }

            if (result != null) {
                String flr =salleProf.getText();
//                System.out.println(flr);
                result_field.setText(result.getText());
                int s = Integer.parseInt(result.getText());
                String reqUpdate ="update stagiaire s set s.statut = 9 where idetud = "+s;
                cnx.executerSelect(reqUpdate);
                String req ="select s.last_name, s.first_name,s.seance_absn,st.statut  from stagiaire s , statut st where (s.idgroupe = (select codegroupe from groupe where nomgroupe= '"+flr+"') and st.idstatut=s.statut)";
                rs = cnx.executerSelect(req);
                tabelModel = (DefaultTableModel) Tblstagiere.getModel();
                tabelModel.setRowCount(0);
                    try {         
                                  while ( rs.next()){

                                  tabelModel.addRow(
                                          new Object[]{
                                      rs.getString(1), 
                                      rs.getString(2), 
                                      rs.getInt(3), 
                                      rs.getString(4)
                                               });



            }
                    }catch (SQLException ex) {
                      System.out.println(ex);
            }

                
                
 }
 

            
        } while (true);
    }

    @Override
    public Thread newThread(Runnable r) {
        Thread t = new Thread(r, "My Thread");
        t.setDaemon(true);
        return t;
    }
}
